import React, { useEffect, useMemo, useState } from 'react';
import { Alert, Image, SafeAreaView, ScrollView, StatusBar, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import * as ImagePicker from 'expo-image-picker';

const API = 'https://chamabebidas.com.br/api';
const C = { bg:'#101114', card:'#1D2028', card2:'#252A34', line:'#343A46', text:'#FFFFFF', muted:'#A7ABB4', gold:'#FFC107', green:'#22C55E', red:'#EF4444' };
type Screen='login'|'register'|'home'|'store'|'cart'|'profile';
type Store={id:any; name?:string; store_name?:string; nome?:string; address?:string; phone?:string; photo?:string; logo?:string};
type Product={id:any; name?:string; title?:string; product_name?:string; nome?:string; price?:any; preco?:any; category?:string; image?:string; store_id?:any};

const demoStores: Store[] = [{id:1, store_name:'Chama Adega', address:'Tatuí - SP'}];
const demoProducts: Product[] = [{id:1,name:'Cerveja lata gelada',price:5.5,category:'Cervejas'},{id:2,name:'Gelo 5kg',price:10,category:'Gelo'}];

async function apiGet(paths:string[]) {
  for (const p of paths) {
    try { const r = await fetch(`${API}${p}`); if (r.ok) return await r.json(); } catch {}
  }
  return null;
}
async function apiPost(paths:string[], body:any) {
  for (const p of paths) {
    try { const r = await fetch(`${API}${p}`, {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify(body)}); if (r.ok) return await r.json(); } catch {}
  }
  return null;
}
const digits=(v:string)=>String(v||'').replace(/\D/g,'');
const storeName=(s:Store)=>s.store_name||s.name||s.nome||'Adega';
const prodName=(p:Product)=>p.name||p.title||p.product_name||p.nome||'Produto';
const money=(n:any)=>`R$ ${Number(n||0).toFixed(2).replace('.',',')}`;

export default function App(){
  const [screen,setScreen]=useState<Screen>('login');
  const [name,setName]=useState(''); const [cpf,setCpf]=useState(''); const [phone,setPhone]=useState(''); const [password,setPassword]=useState(''); const [photo,setPhoto]=useState(''); const [documentPhoto,setDocumentPhoto]=useState('');
  const [stores,setStores]=useState<Store[]>([]); const [store,setStore]=useState<Store|null>(null); const [products,setProducts]=useState<Product[]>([]); const [cart,setCart]=useState<any[]>([]); const [query,setQuery]=useState(''); const [loading,setLoading]=useState(false);
  useEffect(()=>{ boot(); },[]);
  async function boot(){ const saved=await AsyncStorage.getItem('clientUser'); const logged=await AsyncStorage.getItem('clientLoggedIn'); if(saved&&logged==='yes'){const u=JSON.parse(saved); setName(u.name||''); setCpf(u.cpf||''); setPhone(u.phone||''); setPhoto(u.photo||''); setDocumentPhoto(u.documentPhoto||''); setScreen('home');} await loadStores(); }
  async function loadStores(){ setLoading(true); const d=await apiGet(['/stores','/store','/adegas','/shops']); const arr=Array.isArray(d)?d:(d?.stores||d?.data||d?.adegas||[]); setStores(Array.isArray(arr)&&arr.length?arr:demoStores); setLoading(false); }
  async function login(){ if(!cpf||!password) return Alert.alert('Atenção','Digite CPF e senha.'); const remote=await apiPost(['/customers/login','/clients/login','/login/client'],{cpf:digits(cpf),password}); let u=remote?.user||remote?.client||remote?.customer; if(!u){ const saved=await AsyncStorage.getItem('clientUser'); if(saved){const local=JSON.parse(saved); if(digits(local.cpf)===digits(cpf)&&local.password===password) u=local; }} if(!u) return Alert.alert('Login inválido','CPF ou senha incorretos.'); setName(u.name||u.nome||''); setPhone(u.phone||u.telefone||''); setPhoto(u.photo||''); setDocumentPhoto(u.documentPhoto||''); await AsyncStorage.setItem('clientUser',JSON.stringify({...u,cpf,password})); await AsyncStorage.setItem('clientLoggedIn','yes'); setScreen('home'); loadStores(); }
  async function register(){ if(!name||!cpf||!phone||!password) return Alert.alert('Atenção','Preencha nome, CPF, telefone e senha.'); const body={name,nome:name,cpf:digits(cpf),phone,telefone:phone,password,senha:password,photo,documentPhoto,document_photo:documentPhoto}; const remote=await apiPost(['/customers/register','/clients/register','/customers','/clients'],body); const user=remote?.user||remote?.client||remote?.customer||body; await AsyncStorage.setItem('clientUser',JSON.stringify(user)); await AsyncStorage.setItem('clientLoggedIn','yes'); setScreen('home'); }
  async function pick(kind:'photo'|'doc'){ const perm=await ImagePicker.requestMediaLibraryPermissionsAsync(); if(!perm.granted) return Alert.alert('Permissão','Permita acesso às fotos.'); const r=await ImagePicker.launchImageLibraryAsync({mediaTypes:ImagePicker.MediaTypeOptions.Images,quality:.75}); if(!r.canceled&&r.assets?.[0]?.uri){ kind==='photo'?setPhoto(r.assets[0].uri):setDocumentPhoto(r.assets[0].uri); }}
  async function openStore(s:Store){ setStore(s); setProducts([]); setScreen('store'); const d=await apiGet([`/stores/${s.id}/products`,`/products?store_id=${s.id}`,`/products/store/${s.id}`]); const arr=Array.isArray(d)?d:(d?.products||d?.data||[]); setProducts(Array.isArray(arr)&&arr.length?arr:demoProducts.filter(p=>!p.store_id||String(p.store_id)===String(s.id))); }
  function add(p:Product){ setCart(c=>{const i=c.findIndex(x=>String(x.id)===String(p.id)); if(i>=0){const n=[...c]; n[i].qty++; return n;} return [...c,{...p,qty:1}];}); }
  const total=useMemo(()=>cart.reduce((s,p)=>s+Number(p.price||p.preco||0)*p.qty,0),[cart]);
  async function finish(){ if(!store||!cart.length) return; const body={storeId:store.id,store_id:store.id,customerName:name,customerPhone:phone,customerCpf:cpf,items:cart,total,total_amount:total,status:'pending'}; const r=await apiPost(['/orders','/pedidos'],body); Alert.alert('Pedido enviado', r?'Seu pedido foi enviado para a adega.':'Pedido salvo no app. Verifique a API.'); setCart([]); setScreen('home'); }
  async function logout(){await AsyncStorage.removeItem('clientLoggedIn'); setScreen('login');}
  if(screen==='login') return <SafeAreaView style={s.safe}><StatusBar barStyle="light-content"/><View style={s.center}><Text style={s.logo}>🍺</Text><Text style={s.title}>CHAMA ADEGA</Text><TextInput style={s.input} placeholder="CPF" placeholderTextColor={C.muted} value={cpf} onChangeText={setCpf} keyboardType="number-pad"/><TextInput style={s.input} placeholder="Senha" placeholderTextColor={C.muted} value={password} onChangeText={setPassword} secureTextEntry/><TouchableOpacity style={s.btn} onPress={login}><Text style={s.btnT}>ENTRAR</Text></TouchableOpacity><TouchableOpacity onPress={()=>setScreen('register')}><Text style={s.link}>Criar cadastro do cliente</Text></TouchableOpacity></View></SafeAreaView>;
  if(screen==='register') return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.pad}><Text style={s.h1}>Cadastro do cliente</Text><TextInput style={s.input} placeholder="Nome completo" placeholderTextColor={C.muted} value={name} onChangeText={setName}/><TextInput style={s.input} placeholder="CPF" placeholderTextColor={C.muted} value={cpf} onChangeText={setCpf} keyboardType="number-pad"/><TextInput style={s.input} placeholder="Telefone/WhatsApp" placeholderTextColor={C.muted} value={phone} onChangeText={setPhone} keyboardType="phone-pad"/><TextInput style={s.input} placeholder="Senha" placeholderTextColor={C.muted} value={password} onChangeText={setPassword} secureTextEntry/><TouchableOpacity style={s.pick} onPress={()=>pick('photo')}><Text style={s.text}>📷 Foto do cliente {photo?'✅':''}</Text></TouchableOpacity><TouchableOpacity style={s.pick} onPress={()=>pick('doc')}><Text style={s.text}>🪪 Foto do documento {documentPhoto?'✅':''}</Text></TouchableOpacity><TouchableOpacity style={s.btn} onPress={register}><Text style={s.btnT}>CADASTRAR</Text></TouchableOpacity><TouchableOpacity onPress={()=>setScreen('login')}><Text style={s.link}>Voltar para login</Text></TouchableOpacity></ScrollView></SafeAreaView>;
  if(screen==='store') return <SafeAreaView style={s.safe}><View style={s.top}><TouchableOpacity onPress={()=>setScreen('home')}><Text style={s.back}>‹</Text></TouchableOpacity><Text style={s.hTitle}>{storeName(store!)}</Text><TouchableOpacity onPress={()=>setScreen('cart')}><Text style={s.cart}>🛒 {cart.length}</Text></TouchableOpacity></View><ScrollView contentContainerStyle={s.pad}>{products.map(p=><View key={String(p.id)} style={s.card}><Text style={s.picon}>🍾</Text><View style={{flex:1}}><Text style={s.cardTitle}>{prodName(p)}</Text><Text style={s.muted}>{p.category||'Bebidas'}</Text><Text style={s.price}>{money(p.price||p.preco)}</Text></View><TouchableOpacity style={s.add} onPress={()=>add(p)}><Text style={s.addT}>+</Text></TouchableOpacity></View>)}</ScrollView></SafeAreaView>;
  if(screen==='cart') return <SafeAreaView style={s.safe}><View style={s.top}><TouchableOpacity onPress={()=>setScreen(store?'store':'home')}><Text style={s.back}>‹</Text></TouchableOpacity><Text style={s.hTitle}>Carrinho</Text><View/></View><ScrollView contentContainerStyle={s.pad}>{cart.map(p=><View key={String(p.id)} style={s.card}><Text style={s.cardTitle}>{prodName(p)} x{p.qty}</Text><Text style={s.price}>{money(Number(p.price||p.preco||0)*p.qty)}</Text></View>)}<Text style={s.total}>Total: {money(total)}</Text><TouchableOpacity style={s.btn} onPress={finish}><Text style={s.btnT}>FINALIZAR PEDIDO</Text></TouchableOpacity></ScrollView></SafeAreaView>;
  if(screen==='profile') return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.pad}><Text style={s.h1}>Meu perfil</Text>{photo?<Image source={{uri:photo}} style={s.avatar}/>:null}<Text style={s.text}>Nome: {name}</Text><Text style={s.text}>CPF: {cpf}</Text><Text style={s.text}>Telefone: {phone}</Text><Text style={s.text}>Documento: {documentPhoto?'Enviado':'Não enviado'}</Text><TouchableOpacity style={s.pick} onPress={()=>setScreen('home')}><Text style={s.text}>Voltar</Text></TouchableOpacity><TouchableOpacity style={s.out} onPress={logout}><Text style={s.outT}>Sair</Text></TouchableOpacity></ScrollView></SafeAreaView>;
  return <SafeAreaView style={s.safe}><View style={s.hero}><View><Text style={s.kicker}>ADEGAS PERTO DE VOCÊ</Text><Text style={s.hello}>Olá, {name||'cliente'}</Text><Text style={s.muted}>🟢 Aberto agora • Entrega rápida</Text></View><TouchableOpacity onPress={()=>setScreen('profile')}><Text style={s.profile}>👤</Text></TouchableOpacity></View><View style={s.pad2}><TextInput style={s.input} placeholder="Buscar adega..." placeholderTextColor={C.muted} value={query} onChangeText={setQuery}/><TouchableOpacity style={s.reload} onPress={loadStores}><Text style={s.text}>{loading?'Carregando...':'Atualizar adegas da API'}</Text></TouchableOpacity></View><ScrollView contentContainerStyle={s.pad}>{stores.filter(x=>!query||storeName(x).toLowerCase().includes(query.toLowerCase())).map(st=><TouchableOpacity key={String(st.id)} style={s.store} onPress={()=>openStore(st)}><Text style={s.picon}>🍺</Text><View style={{flex:1}}><Text style={s.cardTitle}>{storeName(st)}</Text><Text style={s.muted}>{st.address||'Entrega disponível'}</Text></View><Text style={s.go}>›</Text></TouchableOpacity>)}</ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:C.bg},center:{flex:1,justifyContent:'center',padding:24},pad:{padding:16,paddingBottom:40},pad2:{paddingHorizontal:16},logo:{fontSize:64,textAlign:'center'},title:{color:C.text,fontSize:32,fontWeight:'900',textAlign:'center',marginBottom:20},h1:{color:C.text,fontSize:26,fontWeight:'900',marginBottom:12},input:{backgroundColor:C.card,borderColor:C.line,borderWidth:1,borderRadius:16,padding:15,color:C.text,fontWeight:'700',marginTop:10},btn:{backgroundColor:C.gold,borderRadius:16,padding:17,alignItems:'center',marginTop:14},btnT:{color:'#111',fontWeight:'900'},link:{color:C.gold,textAlign:'center',fontWeight:'900',marginTop:18},pick:{backgroundColor:C.card2,borderRadius:16,padding:16,marginTop:12,borderWidth:1,borderColor:C.line},text:{color:C.text,fontWeight:'800'},muted:{color:C.muted,fontWeight:'700',marginTop:4},top:{height:64,backgroundColor:C.bg,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:16},back:{color:C.text,fontSize:42},hTitle:{color:C.text,fontSize:18,fontWeight:'900'},cart:{color:C.gold,fontWeight:'900',fontSize:17},card:{backgroundColor:C.card,borderRadius:22,padding:16,marginBottom:12,borderWidth:1,borderColor:C.line,flexDirection:'row',alignItems:'center',gap:12},picon:{fontSize:36},cardTitle:{color:C.text,fontSize:18,fontWeight:'900'},price:{color:C.gold,fontSize:18,fontWeight:'900',marginTop:6},add:{width:44,height:44,borderRadius:14,backgroundColor:C.gold,alignItems:'center',justifyContent:'center'},addT:{color:'#111',fontSize:26,fontWeight:'900'},total:{color:C.text,fontSize:26,fontWeight:'900',textAlign:'right',marginVertical:16},hero:{margin:16,marginTop:36,backgroundColor:'#111827',borderRadius:26,padding:18,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},kicker:{color:C.gold,fontSize:12,fontWeight:'900'},hello:{color:C.text,fontSize:25,fontWeight:'900',marginTop:4},profile:{fontSize:34},reload:{backgroundColor:C.card2,borderRadius:14,padding:13,alignItems:'center',marginTop:10,borderWidth:1,borderColor:C.line},store:{backgroundColor:C.card,borderRadius:24,padding:17,marginBottom:13,borderWidth:1,borderColor:C.line,flexDirection:'row',alignItems:'center',gap:12},go:{color:C.gold,fontSize:34,fontWeight:'900'},avatar:{width:96,height:96,borderRadius:48,alignSelf:'center',marginBottom:14},out:{borderColor:C.red,borderWidth:1,borderRadius:16,padding:16,alignItems:'center',marginTop:16},outT:{color:C.red,fontWeight:'900'}});
