
import React,{useEffect,useMemo,useState}from'react';
import{Alert,FlatList,Linking,SafeAreaView,ScrollView,StatusBar as RNStatusBar,StyleSheet,Text,TextInput,TouchableOpacity,View}from'react-native';
import{StatusBar}from'expo-status-bar';
import AsyncStorage from'@react-native-async-storage/async-storage';

const API='https://chamabebidas.com.br/api';
const C={bg:'#08090C',panel:'#12151A',panel2:'#1B1E24',line:'#2B3038',text:'#FFF',muted:'#A7ABB4',yellow:'#FFD000',green:'#21D060',red:'#FF3B4E'};
type Product={id:any,name?:string,title?:string,price?:number,product_name?:string};
type Store={id:any,name?:string,store_name?:string,address?:string};
const DEMO_STORES:Store[]=[{id:1,store_name:'Adega Islamonteiro33',address:'Tatuí - SP'}];
const DEMO_PRODUCTS:Product[]=[{id:1,name:'Cerveja lata',price:5.5},{id:2,name:'Gelo',price:10},{id:3,name:'Energético',price:12.9},{id:4,name:'Vodka',price:39.9}];

export default function App(){
const[screen,setScreen]=useState<'login'|'home'|'store'|'cart'|'tracking'|'orders'>('login');
const[name,setName]=useState(''),[phone,setPhone]=useState(''),[address,setAddress]=useState('');
const[stores,setStores]=useState<Store[]>([]),[store,setStore]=useState<Store|null>(null),[products,setProducts]=useState<Product[]>([]),[cart,setCart]=useState<any[]>([]),[order,setOrder]=useState<any|null>(null);
useEffect(()=>{boot()},[]);
async function boot(){let n=await AsyncStorage.getItem('clientName'),p=await AsyncStorage.getItem('clientPhone'),a=await AsyncStorage.getItem('clientAddress');if(n){setName(n);setPhone(p||'');setAddress(a||'');setScreen('home')}loadStores()}
async function login(){if(!name.trim()||!phone.trim())return Alert.alert('Atenção','Digite nome e telefone.');await AsyncStorage.setItem('clientName',name);await AsyncStorage.setItem('clientPhone',phone);await AsyncStorage.setItem('clientAddress',address);setScreen('home')}
async function loadStores(){try{let r=await fetch(`${API}/stores`);let d=await r.json();setStores(Array.isArray(d)?d:DEMO_STORES)}catch{setStores(DEMO_STORES)}}
async function openStore(s:Store){setStore(s);try{let r=await fetch(`${API}/stores/${s.id}/products`);let d=await r.json();let arr=Array.isArray(d)?d:d.products||d.data;setProducts(Array.isArray(arr)?arr:DEMO_PRODUCTS)}catch{setProducts(DEMO_PRODUCTS)}setScreen('store')}
function add(p:Product){setCart(c=>{let i=c.findIndex(x=>x.id===p.id);if(i>=0){let n=[...c];n[i]={...n[i],qty:n[i].qty+1};return n}return[...c,{...p,qty:1}]})}
function price(p:any){return Number(p.price||0)}
const total=useMemo(()=>cart.reduce((s,p)=>s+price(p)*p.qty,0),[cart]);
async function checkout(){if(!store||!cart.length)return;let payload={storeId:store.id,customerName:name,customerPhone:phone,address,items:cart,total,paymentMethod:'pix',status:'pending'};try{let r=await fetch(`${API}/orders`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});let d=await r.json();setOrder(d.order||d||{id:'PED_DEMO',...payload})}catch{setOrder({id:'PED_DEMO',...payload})}setCart([]);setScreen('tracking')}
function zap(){Linking.openURL(`https://wa.me/55${phone.replace(/\D/g,'')}`)}
if(screen==='login')return <SafeAreaView style={s.bg}><StatusBar style="light"/><RNStatusBar barStyle="light-content" backgroundColor={C.bg}/><ScrollView contentContainerStyle={s.login}><View style={s.logo}><Text style={{fontSize:42}}>🍻</Text></View><Text style={s.title}>Chama Bebidas</Text><Text style={s.sub}>Bebidas rápidas na sua casa</Text><TextInput style={s.input} placeholder="Seu nome" placeholderTextColor={C.muted} value={name} onChangeText={setName}/><TextInput style={s.input} placeholder="WhatsApp" placeholderTextColor={C.muted} value={phone} onChangeText={setPhone} keyboardType="phone-pad"/><TextInput style={s.input} placeholder="Endereço de entrega" placeholderTextColor={C.muted} value={address} onChangeText={setAddress}/><Button title="ENTRAR" onPress={login}/></ScrollView></SafeAreaView>;
if(screen==='store'&&store)return <SafeAreaView style={s.bg}><Header title={store.store_name||store.name||'Adega'} back={()=>setScreen('home')}/><FlatList data={products} keyExtractor={i=>String(i.id)} contentContainerStyle={{padding:16,paddingBottom:100}} renderItem={({item})=><View style={s.product}><View><Text style={s.pname}>{item.name||item.title||item.product_name}</Text><Text style={s.sub}>Produto disponível</Text><Text style={s.price}>R$ {price(item).toFixed(2)}</Text></View><TouchableOpacity style={s.add} onPress={()=>add(item)}><Text style={s.addText}>+</Text></TouchableOpacity></View>}/>{cart.length>0&&<TouchableOpacity style={s.cartBar} onPress={()=>setScreen('cart')}><Text style={s.cartText}>Ver carrinho • {cart.length} itens • R$ {total.toFixed(2)}</Text></TouchableOpacity>}</SafeAreaView>;
if(screen==='cart')return <SafeAreaView style={s.bg}><Header title="Carrinho" back={()=>setScreen('store')}/><ScrollView contentContainerStyle={{padding:16}}>{cart.map(p=><View key={p.id} style={s.line}><Text style={s.white}>{p.qty}x {p.name||p.title}</Text><Text style={s.white}>R$ {(price(p)*p.qty).toFixed(2)}</Text></View>)}<View style={s.panel}><Text style={s.pname}>Entrega</Text><Text style={s.sub}>{address||'Endereço não informado'}</Text><Text style={s.big}>Total: R$ {total.toFixed(2)}</Text><Button title="FINALIZAR PEDIDO" onPress={checkout}/></View></ScrollView></SafeAreaView>;
if(screen==='tracking')return <SafeAreaView style={s.bg}><Header title="Acompanhar pedido" back={()=>setScreen('home')}/><View style={s.track}><Text style={s.big}>Pedido #{order?.id||'novo'}</Text><Step active title="Pedido recebido"/><Step active={order?.status!=='pending'} title="Adega preparando"/><Step title="Entregador a caminho"/><Step title="Entregue"/><Button title="CHAMAR NO WHATSAPP" onPress={zap}/></View></SafeAreaView>;
return <SafeAreaView style={s.bg}><View style={s.top}><Text style={s.hello}>Olá, {name||'Cliente'}</Text><TouchableOpacity onPress={()=>setScreen('cart')}><Text style={s.cartIcon}>🛒 {cart.length}</Text></TouchableOpacity></View><ScrollView contentContainerStyle={{padding:16,paddingBottom:80}}><View style={s.hero}><Text style={s.title2}>Sua bebida chegou</Text><Text style={s.sub}>Escolha uma adega e faça seu pedido</Text></View><Text style={s.section}>Adegas próximas</Text>{stores.map(st=><TouchableOpacity key={st.id} style={s.store} onPress={()=>openStore(st)}><Text style={{fontSize:34}}>🏪</Text><View style={{flex:1}}><Text style={s.pname}>{st.store_name||st.name||'Adega'}</Text><Text style={s.sub}>{st.address||'Entrega rápida'}</Text></View><Text style={s.arrow}>›</Text></TouchableOpacity>)}</ScrollView></SafeAreaView>
}
function Button({title,onPress}:any){return <TouchableOpacity style={s.btn} onPress={onPress}><Text style={s.btnText}>{title}</Text></TouchableOpacity>}
function Header({title,back}:any){return <View style={s.header}><TouchableOpacity onPress={back}><Text style={s.back}>‹</Text></TouchableOpacity><Text style={s.htitle}>{title}</Text><Text style={s.back}> </Text></View>}
function Step({title,active}:any){return <View style={s.step}><View style={[s.dot,active&&{backgroundColor:C.yellow}]}/><Text style={active?s.white:s.sub}>{title}</Text></View>}
const s=StyleSheet.create({bg:{flex:1,backgroundColor:C.bg},login:{flexGrow:1,justifyContent:'center',padding:24},logo:{width:92,height:92,borderRadius:46,backgroundColor:C.yellow,alignItems:'center',justifyContent:'center',alignSelf:'center',marginBottom:22},title:{color:C.text,fontSize:31,fontWeight:'900',textAlign:'center'},sub:{color:C.muted,fontWeight:'700'},input:{backgroundColor:C.panel2,color:C.text,borderRadius:12,padding:16,marginTop:12,borderWidth:1,borderColor:C.line},btn:{backgroundColor:C.yellow,borderRadius:12,padding:16,alignItems:'center',marginTop:16},btnText:{color:'#111',fontWeight:'900'},top:{paddingTop:45,paddingHorizontal:18,paddingBottom:18,backgroundColor:C.bg,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},hello:{color:C.text,fontSize:22,fontWeight:'900'},cartIcon:{color:C.yellow,fontWeight:'900',fontSize:18},hero:{backgroundColor:C.panel,borderRadius:20,padding:20,borderWidth:1,borderColor:C.line},title2:{color:C.text,fontSize:28,fontWeight:'900'},section:{color:C.text,fontSize:19,fontWeight:'900',marginTop:22,marginBottom:12},store:{backgroundColor:C.panel,borderRadius:18,padding:16,marginBottom:12,flexDirection:'row',alignItems:'center',gap:14,borderWidth:1,borderColor:C.line},pname:{color:C.text,fontSize:17,fontWeight:'900'},arrow:{color:C.muted,fontSize:36},header:{height:68,backgroundColor:C.bg,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:18},back:{color:C.text,fontSize:38},htitle:{color:C.text,fontSize:18,fontWeight:'900'},product:{backgroundColor:C.panel,borderRadius:18,padding:16,marginBottom:12,flexDirection:'row',justifyContent:'space-between',alignItems:'center',borderWidth:1,borderColor:C.line},price:{color:C.yellow,fontWeight:'900',fontSize:18,marginTop:8},add:{width:48,height:48,borderRadius:24,backgroundColor:C.yellow,alignItems:'center',justifyContent:'center'},addText:{color:'#111',fontSize:28,fontWeight:'900'},cartBar:{position:'absolute',left:12,right:12,bottom:15,backgroundColor:C.yellow,borderRadius:14,padding:16,alignItems:'center'},cartText:{color:'#111',fontWeight:'900'},line:{flexDirection:'row',justifyContent:'space-between',padding:16,borderBottomWidth:1,borderBottomColor:C.line},white:{color:C.text,fontWeight:'900'},panel:{backgroundColor:C.panel,borderRadius:18,padding:16,marginTop:20,borderWidth:1,borderColor:C.line},big:{color:C.text,fontSize:24,fontWeight:'900',marginTop:20},track:{margin:16,backgroundColor:C.panel,borderRadius:18,padding:18,borderWidth:1,borderColor:C.line},step:{flexDirection:'row',alignItems:'center',gap:12,paddingVertical:14},dot:{width:18,height:18,borderRadius:9,backgroundColor:C.panel2,borderWidth:1,borderColor:C.line}});
