workflows:
  android-apk:
    name: Android APK Cliente Premium
    max_build_duration: 60
    environment:
      node: latest
    scripts:
      - npm install
      - npm install -g eas-cli
      - eas build --platform android --profile preview --non-interactive
    artifacts:
      - build/**/outputs/**/*.apk
